version: '3.7'
services:
    web:
        build: . 
        image: django-sandbox:latest
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/src
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1