version: '3.7'
services:
    db:
        image: postgres:12.0-alpine
        volumes:
            - .:/databank
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    web:
        build: . 
        image: django-sandbox:latest
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 0.0.0.0 127.0.0.1 [::1]
            - SQL_ENGINE=django.db.backends.postgresql
            - SQL_DATABASE=postgres
            - SQL_USER=postgres
            - SQL_PASSWORD=postgres
            - SQL_HOST=db
            - SQL_PORT=5432
        depends_on:
          - db
        links:
          - db:db